version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  ingest-api:
    build: ./ingest-api-localhost
    # Build the image with name and tag
    image: ingest-api:1.7
    hostname: ingest-api
    container_name: ingest-api
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
      - HOST_GLOBUS_MOUNT_DIR=/hubmap-data
    volumes:
      # Mount the source code to container
      - "../src/ingest-api:/usr/src/app/src"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount Globus data
      - "/hubmap-data:/hubmap-data"
    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
