version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  ingest-api:
    build: 
      context: ./ingest-api-test
      args:
        # The commons github branch to be used during image build (default to master if not set or null)
        - COMMONS_BRANCH=${COMMONS_BRANCH:-master}
    # Build the image with name and tag
    image: ingest-api:1.11
    hostname: ingest-api
    container_name: ingest-api
    init: true
    restart: always
    # Map host machine port 80, 443 to container ports 8080 and 4430
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "80:8080"
      - "443:4430"
      # ingest-pipeline
      - "5555:5555"
      - "5556:5556"
      # ingest-api on http 7777 to be used by airflow
      - "7777:7777"
    environment:
      # Both UID and GID of user `hive` being used by the container
      # uid=68728(hive) gid=23629(hive) groups=23629(hive),1011(docker)
      - USER_HIVE_UID=${HOST_UID:-68728}
      - USER_HIVE_GID=${HOST_GID:-23629}
      # Only UID of user `shirey` being used by the container
      # uid=50069(shirey) gid=23653(pitthive) groups=992(docker),23653(pitthive),23684(hivetest)
      - USER_SHIREY_UID=${HOST_UID:-50069}
      # GID of group `hubmap` and GID of group `hubseq` being used by the container
      # hubmap:*:24357:blood
      # hubseq:*:24358:blood
      - GROUP_HUBMAP_GID=${GROUP_HUBMAP_GID:-24357}
      - GROUP_HUBSEQ_GID=${GROUP_HUBSEQ_GID:-24358}
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "../src/ingest-api/instance:/usr/src/app/src/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount ssl certificates from host to container
      - "/etc/pki/nginx:/etc/pki/nginx"
      # Mount conf.d to the nginx conf.d on container
      - "./ingest-api-test/nginx/conf.d:/etc/nginx/conf.d"
      # favicon.ico
      - "./ingest-api-test/nginx/html:/usr/share/nginx/html"
      # Workflow scrath directory
      - "/hive/hubmap-test/scratch:/hubmap-scratch"
      # Airflow static files
      - "/hive/users/hive/hubmap/hivevm192-test/venv/lib/python3.6/site-packages/airflow/www:/airflow-static"
      # Flower static files
      - "/hive/users/hive/hubmap/hivevm192-test/venv/lib/python3.6/site-packages/flower:/flower-static"
      # Mount Globus data
      - "/hive/hubmap-test/lz:/hive/hubmap-test/lz"
      # assets
      - "/hive/hubmap-test/assets:/usr/src/assets"
    networks:
      - hubmap

networks:
  hubmap:
