import hm_uuid
import pprint

hm_uuid.init()
r0=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r0)
r1=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r1)
r2=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r2)
r3=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r3)
r4=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r4)
r5=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r5)
r6=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r6)
r7=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r7)
r8=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r8)
r9=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r9)
r10=hm_uuid.worker.newUUIDTest(True, None, "Donor", "akjasdfadsa", "shireytest@pitt.edu")
print(r10)
print(hm_uuid.worker.getIdInfo(r0))
print(hm_uuid.worker.getIdInfo(r1))
print(hm_uuid.worker.getIdInfo(r2))
print(hm_uuid.worker.getIdInfo(r3))
print(hm_uuid.worker.getIdInfo(r4))
print(hm_uuid.worker.getIdInfo(r5))
print(hm_uuid.worker.getIdInfo(r6))
print(hm_uuid.worker.getIdInfo(r7))
print(hm_uuid.worker.getIdInfo(r8))
print(hm_uuid.worker.getIdInfo(r9))
print(hm_uuid.worker.getIdInfo(r10))