// 20210317101059
// https://raw.githubusercontent.com/hubmapconsortium/commons/test-release/hubmap_commons/hubmap-globus-groups.json
// TEMPORARY FILE FOR GROUPS


export const DATA_ADMIN = "89a69625-99d7-11ea-9366-0e98982705c1";
export const DATA_CURATOR = "75804b96-d4a8-11e9-9da9-0ad4acb67ed4";

export const GROUPS =
[
{
    "description": "All Groups",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "All Components",
    "group_type": "regular",
    "name": "All Components",
    "displayname": "All Components",
    "shortname": "All Components",
    "generateuuid": false
  },
  {
    "description": "Users who have write access to the California Institute of Technology directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "308f5ffc-ed43-11e8-b56a-0e8017bdda58",
    "group_type": "regular",
    "name": "HuBMAP-CalTech-TMC",
    "displayname": "California Institute of Technology TMC",
    "shortname": "TMC - Cal Tech",
    "generateuuid": true,
    "tmc_prefix": "TMCCALT"
  },
  {
    "description": "Users who have access to the Children's Hospital of Philadelphia TMC directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "ee6f749f-c86f-11eb-b35e-4dfdb5d10392",
    "group_type": "regular",
    "name": "HuBMAP-CHOP-TMC",
    "displayname": "TMC - Children's Hospital of Philadelphia",
    "shortname": "TMC - CHOP",
    "generateuuid": true,
    "tmc_prefix": "CHOP"
  },
  {
    "description": "Users who have access to the Pacific Northwest National Laboratory TMC directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "0b8ca9fe-c870-11eb-b35e-4dfdb5d10392",
    "group_type": "regular",
    "name": "HuBMAP-PNNL-TMC",
    "displayname": "TMC - Pacific Northwest National Laboratory",
    "shortname": "TMC - PNNL",
    "generateuuid": true,
    "tmc_prefix": "TMCPNNL"
  },
  {
    "description": "Users who have write access to the Stanford University directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "def5fd76-ed43-11e8-b56a-0e8017bdda58",
    "group_type": "regular",
    "name": "HuBMAP-Stanford-TMC",
    "displayname": "Stanford TMC",
    "shortname": "TMC - Stanford",
    "generateuuid": true,
    "tmc_prefix": "TMCSTAN"
  },
  {
    "description": "Users who have access to the University of Connecticut TMC directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "301615f9-c870-11eb-a8dc-35ce3d8786fe",
    "group_type": "regular",
    "name": "HuBMAP-UCONN-TMC",
    "displayname": "TMC - University of Connecticut",
    "shortname": "TMC - UConn",
    "generateuuid": true,
    "tmc_prefix": "UCONN"
  },
  {
    "description": "Users who have access to the University of California San Diego focusing on female reproduction directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "1fe64d24-c870-11eb-9a03-a9c8d5e16226",
    "group_type": "regular",
    "name": "HuBMAP-UCSD-FEMALE-REPRODUCTIVE-TMC",
    "displayname": "TMC - University of California San Diego focusing on female reproduction",
    "shortname": "TMC - UCSD (Female Reproductive)",
    "generateuuid": true,
    "tmc_prefix": "UCSDFR"
  },
  {
    "description": "Users who have access to the University of California San Diego directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "03b3d854-ed44-11e8-8bce-0e368f3075e8",
    "group_type": "regular",
    "name": "HuBMAP-UCSD-TMC",
    "displayname": "University of California San Diego TMC focusing on kidney",
    "shortname": "TMC - UCSD (Kidney)",
    "generateuuid": true,
    "tmc_prefix": "UCSD"
  },
  {
    "description": "Users who have write access in the University of Florida directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "07a29e4c-ed43-11e8-b56a-0e8017bdda58",
    "group_type": "regular",
    "name": "HuBMAP-UFlorida-TMC",
    "displayname": "University of Florida TMC",
    "shortname": "TMC - UFlorida",
    "generateuuid": true,
    "tmc_prefix": "UFL"
  },
  {
    "description": "Users who have access to the University of Pennsylvania TMC directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "69cb89c4-c870-11eb-b360-4dfdb5d10392",
    "group_type": "regular",
    "name": "HuBMAP-UPENN-TMC",
    "displayname": "TMC - University of Pennsylvania ",
    "shortname": "TMC - UPenn",
    "generateuuid": true,
    "tmc_prefix": "UPENN"
  },
  {
    "description": "Users who have write access to the Vanderbilt University directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "73bb26e4-ed43-11e8-8f19-0a7c1eab007a",
    "group_type": "regular",
    "name": "HuBMAP-Vanderbilt-TMC",
    "displayname": "Vanderbilt TMC",
    "shortname": "TMC - Vanderbilt",
    "generateuuid": true,
    "tmc_prefix": "TMCVAN"
  },
  {
    "description": "Users who have access to the Broad Institute RTI directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "9c4a56ca-79ac-11ea-8359-0e41da796b5d",
    "group_type": "regular",
    "name": "HuBMAP-Broad-RTI",
    "displayname": "Broad Institute RTI",
    "shortname": "RTI - Broad",
    "generateuuid": true,
    "tmc_prefix": "RTIBD"
  },
  {
    "description": "Users who have access to the General Electric RTI directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "5c106f29-ea2d-11e9-85e8-0efb3ba9a670",
    "group_type": "regular",
    "name": "HuBMAP-GE-RTI",
    "displayname": "General Electric RTI",
    "shortname": "RTI - GE",
    "generateuuid": true,
    "tmc_prefix": "RTIGE"
  },
  {
    "description": "Users who have access to the Northwestern RTI directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "76755cd8-79ad-11ea-8293-0a53601d30b5",
    "group_type": "regular",
    "name": "HuBMAP-Northwestern-RTI",
    "displayname": "Northwestern RTI",
    "shortname": "RTI - Northwestern",
    "generateuuid": true,
    "tmc_prefix": "RTINW"
  },
  {
    "description": "Users who have access to the Stanford RTI directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "f5af3a5a-e93c-11e9-8559-0efb3ba9a670",
    "group_type": "regular",
    "name": "HuBMAP-Stanford-RTI",
    "displayname": "Stanford RTI",
    "shortname": "RTI - Stanford",
    "generateuuid": true,
    "tmc_prefix": "RTIST"
  },
  {
    "description": "Users who have access to the Cal Tech TTD directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "ab7db177-79ad-11ea-835a-0e41da796b5d",
    "group_type": "regular",
    "name": "HuBMAP-CalTech-TTD",
    "displayname": "Cal Tech TTD",
    "shortname": "TTD - Cal Tech",
    "generateuuid": true,
    "tmc_prefix": "TTDCT"
  },
  {
    "description": "Users who have access to the Harvard TTD directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "ca46f893-79ad-11ea-b66c-0a990c2810ad",
    "group_type": "regular",
    "name": "HuBMAP-Harvard-TTD",
    "displayname": "Harvard TTD",
    "shortname": "TTD - Harvard",
    "generateuuid": true,
    "tmc_prefix": "TTDHV"
  },
  {
    "description": "Users who have access to the Pacific Northwest National Laboratory TTD directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "878a6a26-c870-11eb-a8dc-35ce3d8786fe",
    "group_type": "regular",
    "name": "HuBMAP-PNNL-TTD",
    "displayname": "TTD - Pacific Northwest National Laboratory",
    "shortname": "TTD - PNNL",
    "generateuuid": true,
    "tmc_prefix": "TTDPNNL"
  },
  {
    "description": "Users who have access to the Pacific Northwest National Laboratory and Northwestern University TTD directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "972b2a76-c870-11eb-a8dc-35ce3d8786fe",
    "group_type": "regular",
    "name": "HuBMAP-PNNL-NU-TTD",
    "displayname": "TTD - Pacific Northwest National Laboratory and Northwestern University",
    "shortname": "TTD - PNNL & NU",
    "generateuuid": true,
    "tmc_prefix": "PNNLNU"
  },
  {
    "description": "Users who have access to the Penn State University and Columbia University TTD directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "b148f323-c870-11eb-b360-4dfdb5d10392",
    "group_type": "regular",
    "name": "HuBMAP-PSU-CU-TTD",
    "displayname": "TTD - Penn State University and Columbia University",
    "shortname": "TTD - PSU & CU",
    "generateuuid": true,
    "tmc_prefix": "PSCCU"
  },
  {
    "description": "Users who have access to the Purdue TTD directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "eb5c5345-79ad-11ea-bc85-0ef992ed7ca1",
    "group_type": "regular",
    "name": "HuBMAP-Purdue-TTD",
    "displayname": "Purdue TTD",
    "shortname": "TTD - Purdue",
    "generateuuid": true,
    "tmc_prefix": "TTDPD"
  },
  {
    "description": "Users who have access to the Stanford TTD directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "f677f31f-79b0-11ea-8295-0a53601d30b5",
    "group_type": "regular",
    "name": "HuBMAP-Stanford-TTD",
    "displayname": "Stanford TTD",
    "shortname": "TTD - Stanford",
    "generateuuid": true,
    "tmc_prefix": "TTDST"
  },
  {
    "description": "Users who have access to the University of California San Diego and City of Hope directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "d62c4872-c870-11eb-a8dd-35ce3d8786fe",
    "group_type": "regular",
    "name": "HuBMAP-UCSD-COH-TTD",
    "displayname": "TTD - University of San Diego and City of Hope",
    "shortname": "TTD - UCSD & City of Hope",
    "generateuuid": true,
    "tmc_prefix": "UCSDCOH"
  },
  {
    "description": "Users who have access to the Yale University TTD directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "ea9a6442-c870-11eb-bf37-f92c084a680e",
    "group_type": "regular",
    "name": "HuBMAP-YALE-TTD",
    "displayname": "TTD - Yale University",
    "shortname": "TTD - Yale",
    "generateuuid": true,
    "tmc_prefix": "YALE"
  },
  {
    "description": "Users who have write access to the Lurie Childrens Hospital Demonstration Project directory",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "f2e660d1-f3fd-11ed-bcea-5b6c9dc23028",
    "group_type": "regular",
    "name": "HuBMAP-Lurie-DP",
    "displayname": "Lurie Childrens Hospital DP",
    "shortname": "DP - Lurie",
    "generateuuid": true,
    "tmc_prefix": "LURIE" 
  },
  {
    "description": "Users who have access to the external Human Cell Atlas organization directory.",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "177f92c0-c871-11eb-9a04-a9c8d5e16226",
    "group_type": "regular",
    "name": "HuBMAP-HCA-EXT",
    "displayname": "EXT - Human Cell Atlas",
    "shortname": "EXT - HCA",
    "generateuuid": true,
    "tmc_prefix": "HCA"
  },
  {
    "description": "Users who have write access to the testing folder",
    "data_provider": true,
    "has_subgroups": false,
    "identity_set_properties": null,
    "uuid": "5bd084c8-edc2-11e8-802f-0e368f3075e8",
    "group_type": "regular",
    "name": "HuBMAP-Testing-Group",
    "displayname": "IEC Testing Group",
    "shortname": "IEC Testing Group",
    "generateuuid": true,
    "tmc_prefix": "ZTEST"
  }
];
